# Generated by Django 4.0.1 on 2022-01-13 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('date_created', models.DateField(auto_created=True)),
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('seriesId', models.BigIntegerField()),
                ('result', models.CharField(max_length=100)),
                ('event_date', models.DateField()),
                ('title', models.CharField(max_length=512)),
                ('is_completed', models.BooleanField(default=False)),
                ('last_modified', models.DateField(auto_now=True)),
            ],
        ),
    ]
