# Generated by Django 4.0.1 on 2022-01-13 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='is_completed',
        ),
        migrations.AlterField(
            model_name='game',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
